### ISSUE TITLE
Guzzle 6

### ISSUE THREAD

**Issue by melihovv** [e-moe/guzzle-regexp-mock-plugin#1]
Will there be support for Guzzle 6?

**Comment by e-moe** [comment]
I will try to implement it. but it will take some time.

**Comment by melihovv** [comment]
Спасибо) Очень жду!)

**Comment by tarampampam** [comment]
:fire: [URLs (fixed and regexps-based) mock handler for Guzzle 6](https://github.com/tarampampam/guzzle-url-mock)

**Comment by e-moe** [comment]
sorry for late response. For mocks you can use one of 3rd party libraries e.g. https://github.com/tarampampam/guzzle-url-mock
